apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mall-product
  name: mall-product
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mall-product
  template:
    metadata:
      labels:
        app: mall-product
    spec:
      containers:
      - image: jamesxpenn/mall-product:v1
        name: mall-product
        ports:
        - containerPort: 9002
        env:
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
             name: secret-mysql
             key: username
        - name: MYSQL_PWD
          valueFrom:
            secretKeyRef:
             name: secret-mysql
             key: password             
        - name: MYSQL_HOST
          valueFrom:
            secretKeyRef:
             name: secret-mysql
             key: host                 
        - name: MYSQL_PORT
          valueFrom:
            secretKeyRef:
             name: secret-mysql
             key: port                 
        - name: NACOS_HOST
          valueFrom:
            secretKeyRef:
             name: secret-nacos
             key: host                     
        - name: NACOS_PORT
          valueFrom:
            secretKeyRef:
             name: secret-nacos
             key: port
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: mall-product
  name: mall-product
spec:
  ports:
  - port: 9002
    protocol: TCP
    targetPort: 9002
  selector:
    app: mall-product 