spring:
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_HOST:localhost}:${NACOS_PORT:8848}
  application:
    name: mall-cart
  redis:
    host: ${REDIS_HOST:localhost}
    port: ${REDIS_PORT:6379}
#    password: ${REDIS_PASSWORD:ZirN6PXUqE}

logging:
  pattern:
    console: "[%thread] %-5level %logger{36} - %msg%n"
server:
  port: 9003